---
layout: post
title: "A kombucha journey"
author: "Abbey Yatsko"
categories: sample
tags: [sample]
image: buch.jpeg
---

Kombucha is a slightly controversial beverage, and I’ll admit that I was at first skeptical to all of the kombucha hype. My first introduction to kombucha was through a Buzzfeed article that highlighted the questionable wonders of the base kombucha ‘ingredient’, the SCOBY. A SCOBY, or **S**ymbiotic **C**ulture of **B**acteria and **Y**east (yes, after all this time it does turn out to be an acronym!), is the key part of the brew that makes kombucha… well, kombucha. However, even though the acronym is fun and quirky, the appearance of the SCOBY itself always manages to be shocking and is scary to say the least. That is if you catch a first glance without knowing the power behind this weird, deli-meat looking disc. I assure you that through my own kombucha journey, I have overturned some of the kombucha biases that I once held, and now my SCOBY is like a pet and my kombucha is proudly home brewed - can you tell that we have been a year in quarantine?!

So, with that little bit of background, here’s a little more information on the drink itself if you are not familiar. Kombucha is a fermented tea that tastes both fizzy and a little sour (almost with tinges of vinegar) but can be flavored to include a whole host of fruity tastes. It is known in popular culture for being a health fad (claimed to be filled with probiotics and good for gut health), or a hipster fad (apparently it looks great on an Instagram feed with a green, leafy backdrop), but either way it does have some beneficial qualities to it. The SCOBY that is used to make kombucha is just what the acronym suggests – a collection of bacteria and yeast. These healthy microbes work to ferment the sugars within the tea, and this lactic acid fermentation is known to work as a probiotic and produce B vitamins, with potential positive health benefits. It is noted that kombucha is ever so slightly elevated in alcohol content (due to the fermentation process behind its creation), but it is minuscule and 0.5% content at most – so you don’t have much of a buzz to fret about!

![]({{ site.url }}{{ site.baseurl }}/pics/buch1.jpeg)

I was inspired to make my own kombucha after I became slightly addicted to it. The fruity, effervescent drink is just too much fun to sip on, plus there are positive health claims (of which I am no expert on, but there have been a few peer reviewed studies that suggest these claims hold up to the test of science). I usually am the type of gal to just stick with water, but a small glass of kombucha a day managed to help me keep the trials and tribulations of quarantine at bay. It’s the little things in life, you know? 

Yet, on my way to this kombucha captivation I realized that a) each standard 16oz bottle at the grocery store was usually $4-5, which can significantly add up on a weekly basis, and b) the recycling bin was all of a sudden teetering with glass bottles as I came to the end of the week. Not only was this habit becoming financially unsustainable, but I couldn’t help to notice the glaringly obvious negative environmental impact I was having. So, I turned to the food bloggers and set out to make my own SCOBY – the first step in home-brewing kombucha. 

I have relied on a wonderful blog called [Live Eat Learn](https://www.liveeatlearn.com/) to guide me through the homemade kombucha process, and [this post](https://www.liveeatlearn.com/the-simple-guide-to-kickass-kombucha/#SCOBY) set me on the right track for making my own SCOBY. The process essentially uses store-bought kombucha as a ‘seed’ for the SCOBY, and after many week’s time the SCOBY eventually grows from the combination of store-bought starter kombucha and fresh sweetened tea (that you provide). The sweet tea that you brew up is what the bacteria and yeast feast on while they assemble into a slippery, weird looking circle that is the SCOBY. I’ll note that my first time attempting to make a SCOBY was a failure, as after about a month the SCOBY had yet to form. But you know what they say – get knocked down by a SCOBY-making-failure once, stand up and try it again. After about two months of monitoring a big mason jar on the kitchen table for signs of SCOBY formation, I had finally done it through using a natural, low maintenance fermentation process! See below for a picture of this beauty.

![]({{ site.url }}{{ site.baseurl }}/pics/buch2.jpeg)

I dubbed my SCOBY the name Pando after a giant clonal colony of quaking aspens that is found out in Utah, also named Pando. This aspen grove is essentially a single organism that is united by a huge underground root system from which the clonal colony grows. I thought the name was appropriate for my bacteria and yeast colony, and I hoped that the name would inspire many successful generations for my SCOBY being around. Once Pando the SCOBY was up and running, the fun part of kombucha making officially moved up in the queue. Using the same guide from Live Eat Learn, I followed the basic 2 step process for self sustained home-brewed kombucha, outlined by the first fermentation and the second fermentation. 

In the first fermentation, you prepare a sweet tea using black tea leaves and granulated sugar. Then, the SCOBY is placed into the tea and let to sit at room temperature for a week or so. During this time, the yeast and bacteria work away at the sugars in the tea, effectively ‘eating’ them through the process of fermentation. As this process goes along, you start to see little bubbles rising through the column of tea as carbon dioxide is released from the fermentation process. Over time, the tea solution becomes less sweetened as the SCOBY ferments the sugar, and the liquid starts to take on that characteristic sour-kombucha-y flavor. 

![]({{ site.url }}{{ site.baseurl }}/pics/buch3.jpeg){: style="width: 250px; float: right; margin: 0px 10px"}

The second fermentation then captures the carbon dioxide produced via fermentation in order to naturally make the drink fizzy, similar to the bubbly-ness of soda. Creativity comes in to play as well as you add flavorings from fruit juices or purees, which provide extra sugars for the yeast and bacteria to continually ferment. In this step, the SCOBY is removed and resulting tea from the first fermentation is divided between bottles with an airtight seal. Then, you add the fruit for flavoring to each bottle, seal them up, and wait a few more days as the now-flavored tea continually ferments at room temperature. Then, you move the bottles to the fridge to both chill the kombucha and also slow down the fermenting process. It’s a pretty simple and straightforward 2 step process! 

The process of home-brewing kombucha always had me looking forward to the next fermentation step or development that I observed in my brewing jar. Especially when the monotony of Zoom classes and my PhD work catches up to me, my kombucha project is a perfectly healthy distraction that allows me to switch gears for a second as I monitor the fermentation process or plan out the next week’s flavors. Also, the process literally keeps me on my toes – in the second fermentation, you are essentially pressurizing a bottle of kombucha as carbon dioxide builds up within the solution. A key monitoring step here is to let a little bit of the built-up carbon dioxide gas escape from the bottles every day or two, otherwise catastrophe strikes. Catastrophe did indeed strike for me. I can comment on the value of releasing some of the pressure build up in home-brew kombucha, well, because if you don’t, you will wake up to the sound of exploding glass in the middle of the night. Twice. Let’s just say that paying attention to temperature and sugar volume in the second fermentation cannot be understated!

![]({{ site.url }}{{ site.baseurl }}/pics/buch4.jpeg)

Making your own kombucha gives you the freedom to experiment with different flavors and tastes and adjust them to your liking. So far, I have tinkered with the following flavors: mango orange, lemon ginger, lemon ginger kiwi maple, blackberry lime with ginger, blue-blackberry lime, pomegranate lemon ginger, and mango mandarin. There is so much room for creativity, and I cannot wait for the summer months where I can fresh-pick berries and experiment with even more flavors. 

Another part that makes homemade kombucha SO much better than store bought is that you can control for a lot of waste in the process. In all of my flavoring experiments, I have largely been able to acquire plastic-free fruit. Plus, I use bulk loose-leaf tea, which reduces waste even further (learn more about loose-leaf, zero-waste tea in a past article I wrote). Additionally, I am able to cut down on bottling material needs by simply refilling my bottles with homemade kombucha, eliminating the recycling bin pile-up that results from store purchased kombucha. Glass recycling is a little bit tricky, as it is claimed to be 100% recyclable, but that requires that **all** glass containers make it to the recycling bin in the first place. According to the Glass Packaging Institute, an average of *only one third* of all glass containers are successfully recycled in the US. Even with a perfect process where glass can essentially be recycled endlessly, we see that human behaviors ultimately limit the success of this system.

It feels great to be off of the store-bought kombucha grid. Having independence when it comes to supplying your own food and drink is incredibly empowering, and I’ve been trying to incorporate more and more ways to do so. Not only do you have more autonomy over the process and ethics of where your food comes from, but you have all of the creative liberties in the world! Each home brew is a new opportunity to explore new flavors, and I love the prospect of that journey. 

![]({{ site.url }}{{ site.baseurl }}/pics/buch5.jpeg)

Let me know if you have any suggestions for flavors that I should have a go at in the comment section below! Also, if you want a clone of Pando the SCOBY, I am pretty sure that I can send you part of mine so that you can get home-brewin’ as well. Please reach out if this interests you, as I would LOVE to spread the kombucha joy and help you through this rewarding process - cheers!

abbey
